server.port=9090

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# ????????????? ?????
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# PostgreSQL (Docker / Prod)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shareit}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:shareit}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:shareit}