server:
  port: 8080  # Порт gateway

spring:
  application:
    name: shareIt-gateway

shareit:
  server:
    url: http://shareit-server:9090

logging:
  level:
    ru.practicum.shareit.client.BaseClient: TRACE
    org.springframework.web.client.RestTemplate: TRACE